require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - db/**/*
    - config/environments/*
    - bin/*
  TargetRubyVersion:
    2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

RSpec/NestedGroups:
  MaxNesting: 5 #FIXME: this is too much
